services:
  - name: ssnnews-frontend
    type: web
    env: static
    rootDir: client # Specify the frontend directory
    buildCommand: "npm install && npm run build"
    staticPublishPath: build # Adjusted to match the build output folder
    envVars:
      - key: REACT_APP_API_URL
        value: https://ssnnewsserver.onrender.com/
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html