services:
  - name: ssnnews-backend
    type: web
    env: node
    rootDir: server # Specify the backend directory
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URL
        value: mongodb+srv://swadeshsandesh:2t9Z4PmygBU41RYV@clusterssn.rasxlii.mongodb.net/?retryWrites=true&w=majority&appName=ClusterSSN
      - key: JWT_SECRET
        value: secretkey
    plan: free

  - name: ssnnews-frontend
    type: web
    env: static
    rootDir: client # Specify the frontend directory
    buildCommand: "npm install && npm run build"
    staticPublishPath: build # Adjusted to match the build output folder
    envVars:
      - key: REACT_APP_API_URL
        value: https://ssnnewsserver.onrender.com/
    plan: free